#include <Arduino.h>

//DEFINIMOS LOS PINES DONDE SE VAN A CONECTAR LOS SENSORES ANALOGICOS
#define ANALOG_SENSOR1 A0
#define ANALOG_SENSOR2 A1
#define ANALOG_SENSOR3 A2
#define ANALOG_SENSOR4 A3
#define ANALOG_SENSOR5 A4
#define ANALOG_SENSOR6 A5
//#define ANALOG_SENSOR7 A6
//#define ANALOG_SENSOR8 A7


//DEFINIMOS LOS PINES DONDE SE VA CONECTAR LOS MOTORES
#define MA  3    
#define MB  5
#define MC  12
