#include "SevenSegLib.h"

// Helpers internos (opcional pero recomendado);
static inline void _sevenSeg_setPinsOutput(void)
{
	PIN_OUTPUT(DIR_DISPLAY, SEGA);
	PIN_OUTPUT(DIR_DISPLAY, SEGB);
	PIN_OUTPUT(DIR_DISPLAY, SEGC);
	PIN_OUTPUT(DIR_DISPLAY, SEGD);
	PIN_OUTPUT(DIR_DISPLAY, SEGE);
	PIN_OUTPUT(DIR_DISPLAY, SEGF);
	PIN_OUTPUT(DIR_DISPLAY, SEGG);
}

// ===============================
// ANODO COMUN (AC)
// Encender segmento: LOW
// Apagar segmento:   HIGH
// ===============================
void displayAC(char n)
{
	_sevenSeg_setPinsOutput();

	// Estado base: TODO APAGADO (HIGH)
	PIN_HIGH(PORT_DISPLAY, SEGA);
	PIN_HIGH(PORT_DISPLAY, SEGB);
	PIN_HIGH(PORT_DISPLAY, SEGC);
	PIN_HIGH(PORT_DISPLAY, SEGD);
	PIN_HIGH(PORT_DISPLAY, SEGE);
	PIN_HIGH(PORT_DISPLAY, SEGF);
	PIN_HIGH(PORT_DISPLAY, SEGG);

	switch (n)
	{
		case 0:
		PIN_LOW(PORT_DISPLAY, SEGA);
		PIN_LOW(PORT_DISPLAY, SEGB);
		PIN_LOW(PORT_DISPLAY, SEGC);
		PIN_LOW(PORT_DISPLAY, SEGD);
		PIN_LOW(PORT_DISPLAY, SEGE);
		PIN_LOW(PORT_DISPLAY, SEGF);
		break;

		case 1:
		PIN_LOW(PORT_DISPLAY, SEGB);
		PIN_LOW(PORT_DISPLAY, SEGC);
		break;

		case 2:
		PIN_LOW(PORT_DISPLAY, SEGA);
		PIN_LOW(PORT_DISPLAY, SEGB);
		PIN_LOW(PORT_DISPLAY, SEGD);
		PIN_LOW(PORT_DISPLAY, SEGE);
		PIN_LOW(PORT_DISPLAY, SEGG);
		break;

		case 3:
		PIN_LOW(PORT_DISPLAY, SEGA);
		PIN_LOW(PORT_DISPLAY, SEGB);
		PIN_LOW(PORT_DISPLAY, SEGC);
		PIN_LOW(PORT_DISPLAY, SEGD);
		PIN_LOW(PORT_DISPLAY, SEGG);
		break;

		case 4:
		PIN_LOW(PORT_DISPLAY, SEGB);
		PIN_LOW(PORT_DISPLAY, SEGC);
		PIN_LOW(PORT_DISPLAY, SEGF);
		PIN_LOW(PORT_DISPLAY, SEGG);
		break;

		case 5:
		PIN_LOW(PORT_DISPLAY, SEGA);
		PIN_LOW(PORT_DISPLAY, SEGC);
		PIN_LOW(PORT_DISPLAY, SEGD);
		PIN_LOW(PORT_DISPLAY, SEGF);
		PIN_LOW(PORT_DISPLAY, SEGG);
		break;

		case 6:
		PIN_LOW(PORT_DISPLAY, SEGA);
		PIN_LOW(PORT_DISPLAY, SEGC);
		PIN_LOW(PORT_DISPLAY, SEGD);
		PIN_LOW(PORT_DISPLAY, SEGE);
		PIN_LOW(PORT_DISPLAY, SEGF);
		PIN_LOW(PORT_DISPLAY, SEGG);
		break;

		case 7:
		PIN_LOW(PORT_DISPLAY, SEGA);
		PIN_LOW(PORT_DISPLAY, SEGB);
		PIN_LOW(PORT_DISPLAY, SEGC);
		break;

		case 8:
		PIN_LOW(PORT_DISPLAY, SEGA);
		PIN_LOW(PORT_DISPLAY, SEGB);
		PIN_LOW(PORT_DISPLAY, SEGC);
		PIN_LOW(PORT_DISPLAY, SEGD);
		PIN_LOW(PORT_DISPLAY, SEGE);
		PIN_LOW(PORT_DISPLAY, SEGF);
		PIN_LOW(PORT_DISPLAY, SEGG);
		break;

		case 9:
		PIN_LOW(PORT_DISPLAY, SEGA);
		PIN_LOW(PORT_DISPLAY, SEGB);
		PIN_LOW(PORT_DISPLAY, SEGC);
		PIN_LOW(PORT_DISPLAY, SEGD);
		PIN_LOW(PORT_DISPLAY, SEGF);
		PIN_LOW(PORT_DISPLAY, SEGG);
		break;

		default:
		// Si llega algo raro, queda apagado
		break;
	}
}

// ===============================
// CATODO COMUN (CC)
// Encender segmento: HIGH
// Apagar segmento:   LOW
// ===============================
void displayCC(char n)
{
	_sevenSeg_setPinsOutput();

	// Estado base: TODO APAGADO (LOW)
	PIN_LOW(PORT_DISPLAY, SEGA);
	PIN_LOW(PORT_DISPLAY, SEGB);
	PIN_LOW(PORT_DISPLAY, SEGC);
	PIN_LOW(PORT_DISPLAY, SEGD);
	PIN_LOW(PORT_DISPLAY, SEGE);
	PIN_LOW(PORT_DISPLAY, SEGF);
	PIN_LOW(PORT_DISPLAY, SEGG);

	switch (n)
	{
		case 0:
		PIN_HIGH(PORT_DISPLAY, SEGA);
		PIN_HIGH(PORT_DISPLAY, SEGB);
		PIN_HIGH(PORT_DISPLAY, SEGC);
		PIN_HIGH(PORT_DISPLAY, SEGD);
		PIN_HIGH(PORT_DISPLAY, SEGE);
		PIN_HIGH(PORT_DISPLAY, SEGF);
		break;

		case 1:
		PIN_HIGH(PORT_DISPLAY, SEGB);
		PIN_HIGH(PORT_DISPLAY, SEGC);
		break;

		case 2:
		PIN_HIGH(PORT_DISPLAY, SEGA);
		PIN_HIGH(PORT_DISPLAY, SEGB);
		PIN_HIGH(PORT_DISPLAY, SEGD);
		PIN_HIGH(PORT_DISPLAY, SEGE);
		PIN_HIGH(PORT_DISPLAY, SEGG);
		break;

		case 3:
		PIN_HIGH(PORT_DISPLAY, SEGA);
		PIN_HIGH(PORT_DISPLAY, SEGB);
		PIN_HIGH(PORT_DISPLAY, SEGC);
		PIN_HIGH(PORT_DISPLAY, SEGD);
		PIN_HIGH(PORT_DISPLAY, SEGG);
		break;

		case 4:
		PIN_HIGH(PORT_DISPLAY, SEGB);
		PIN_HIGH(PORT_DISPLAY, SEGC);
		PIN_HIGH(PORT_DISPLAY, SEGF);
		PIN_HIGH(PORT_DISPLAY, SEGG);
		break;

		case 5:
		PIN_HIGH(PORT_DISPLAY, SEGA);
		PIN_HIGH(PORT_DISPLAY, SEGC);
		PIN_HIGH(PORT_DISPLAY, SEGD);
		PIN_HIGH(PORT_DISPLAY, SEGF);
		PIN_HIGH(PORT_DISPLAY, SEGG);
		break;

		case 6:
		PIN_HIGH(PORT_DISPLAY, SEGA);
		PIN_HIGH(PORT_DISPLAY, SEGC);
		PIN_HIGH(PORT_DISPLAY, SEGD);
		PIN_HIGH(PORT_DISPLAY, SEGE);
		PIN_HIGH(PORT_DISPLAY, SEGF);
		PIN_HIGH(PORT_DISPLAY, SEGG);
		break;

		case 7:
		PIN_HIGH(PORT_DISPLAY, SEGA);
		PIN_HIGH(PORT_DISPLAY, SEGB);
		PIN_HIGH(PORT_DISPLAY, SEGC);
		break;

		case 8:
		PIN_HIGH(PORT_DISPLAY, SEGA);
		PIN_HIGH(PORT_DISPLAY, SEGB);
		PIN_HIGH(PORT_DISPLAY, SEGC);
		PIN_HIGH(PORT_DISPLAY, SEGD);
		PIN_HIGH(PORT_DISPLAY, SEGE);
		PIN_HIGH(PORT_DISPLAY, SEGF);
		PIN_HIGH(PORT_DISPLAY, SEGG);
		break;

		case 9:
		PIN_HIGH(PORT_DISPLAY, SEGA);
		PIN_HIGH(PORT_DISPLAY, SEGB);
		PIN_HIGH(PORT_DISPLAY, SEGC);
		PIN_HIGH(PORT_DISPLAY, SEGD);
		PIN_HIGH(PORT_DISPLAY, SEGF);
		PIN_HIGH(PORT_DISPLAY, SEGG);
		break;

		default:
		// Si llega algo raro, queda apagado
		break;
	}
}